// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk28M8J7o_ZzHg6mjT_BFktM4gsa5bCaM',
    appId: '1:716838672538:web:6b3837c385734d9b386723',
    messagingSenderId: '716838672538',
    projectId: 'flutter-13-49d96',
    authDomain: 'flutter-13-49d96.firebaseapp.com',
    storageBucket: 'flutter-13-49d96.firebasestorage.app',
    measurementId: 'G-NNBPKZ4N6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ9CzKWXvXN6AaKK48L7hkgl8AW7FExGc',
    appId: '1:716838672538:android:74694171bf4e7ef2386723',
    messagingSenderId: '716838672538',
    projectId: 'flutter-13-49d96',
    storageBucket: 'flutter-13-49d96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT8Vi7Uymh1tlLhmEM4op2W55pva7Wt9I',
    appId: '1:716838672538:ios:6d2c9699dbfdc8c6386723',
    messagingSenderId: '716838672538',
    projectId: 'flutter-13-49d96',
    storageBucket: 'flutter-13-49d96.firebasestorage.app',
    iosBundleId: 'com.example.firebaseclassproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT8Vi7Uymh1tlLhmEM4op2W55pva7Wt9I',
    appId: '1:716838672538:ios:6d2c9699dbfdc8c6386723',
    messagingSenderId: '716838672538',
    projectId: 'flutter-13-49d96',
    storageBucket: 'flutter-13-49d96.firebasestorage.app',
    iosBundleId: 'com.example.firebaseclassproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk28M8J7o_ZzHg6mjT_BFktM4gsa5bCaM',
    appId: '1:716838672538:web:b884ebfe528f7752386723',
    messagingSenderId: '716838672538',
    projectId: 'flutter-13-49d96',
    authDomain: 'flutter-13-49d96.firebaseapp.com',
    storageBucket: 'flutter-13-49d96.firebasestorage.app',
    measurementId: 'G-5KN9XPR3GE',
  );
}
